# Your developer token for using the Github API.
github_access_token:
jenkins_username:
jenkins_password:

# The new versions of each library.
csdk_version: "202011.00"
versions:
  coremqtt: "v1.0.1"
  corejson: "v2.0.0"
  device-shadow-for-aws-iot-embedded-sdk: "v1.0.1"
  corehttp: "v1.0.0"
  device-defender-for-aws-iot-embedded-sdk: "v1.0.0"
  jobs-for-aws-iot-embedded-sdk: "v1.0.0"
