name: CSDK Release

on:
  workflow_dispatch:
    inputs:
      version_number:
        description: 'Version Number (i.e. 202011.00)'
        required: true
        default: '202011.00'
      corehttp_version:
        description: 'coreHTTP version number'
        required: true
        default: 'v1.0.0'
      corejson_version:
        description: 'coreJSON version number'
        required: true
        default: 'v2.0.0'
      coremqtt_version:
        description: 'coreMQTT version number'
        required: true
        default: 'v1.0.1'
      defender_version:
        description: 'Device Defender version number'
        required: true
        default: 'v1.0.0'
      shadow_version:
        description: "Device Shadow version number"
        required: true
        default: 'v1.0.1'
      jobs_version:
        description: "Jobs version number"
        required: true
        default: 'v1.0.1'

jobs:
  release:
    name: CSDK Release Creation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release-candidate branch
        uses: actions/checkout@v2
        with:
          ref: release-candidate
          submodules: recursive

      - name: Tools setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.5
          architecture:   x64
        env:
          GITHUB_ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
          JENKINS_USERNAME: ${{secrets.JENKINS_USERNAME}}
          JENKINS_PASSWORD: ${{secrets.JENKINS_PASSWORD}}
          JENKINS_API_URL: ${{secrets.JENKINS_API_URL}}
        run: pip install -r tools/release/requirements.txt

      - name: Verify release-candidate branch
        run: |
          python tools/release/release-verify.py \
          --root . \
          --csdk-version ${{github.event.inputs.csdk_version}}
          --corehttp-version ${{github.event.inputs.corehttp_version}}
          --coremqtt-version ${{github.event.inputs.coremqtt_version}}
          --corejson-version ${{github.event.inputs.corejson_version}}
          --device-defender-for-aws-iot-embedded-sdk-version ${{github.event.inputs.defender_version}}
          --device-shadow-for-aws-iot-embedded-sdk-version ${{github.event.inputs.shadow_version}}
          --jobs-for-aws-iot-embedded-sdk-version ${{github.event.inputs.jobs_version}}
